import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import Intro from "./components/Intro";
import MovingBlubs from "./components/MovingBlubs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center relative contain-content">
        <MovingBlubs />
        <Intro />
        {children}
        <TopBar />
      </body>
    </html>
  );
}
